export default `search-products = Search Products
no-products-found = No products found.
add-to-cart = Add to Cart
view-cart = View Cart
cart-items = Cart Items
your-cart-is-empty = Your cart is empty.
online-marketplace = Online Marketplace
cart = Cart
cart-notification-count = {NUMBER($count)} items
checkout = Checkout
quantity = Quantity
searchProducts= Search Products
seller-dashboard = Seller Dashboard
post-product = Post Product
product-name = Product Name
price = Price
product-image = Product Image
submit = Submit
order-management = Order Management
order-details = Order Details
name = Name
address = Address
phone = Phone
product-name = Product Name
quantity = Quantity
price-per-item = Price per Item
total-order-price = Total Order Price
order-id=id
status= Status
`