export default `search-products = Search Products
no-products-found = No products found.
add-to-cart = Add to Cart
view-cart = View Cart
cart-items = Cart Items
your-cart-is-empty = Your cart is empty.
online-marketplace = Online Marketplace
cart = Cart
cart-notification-count = {NUMBER($count)} items
checkout = Checkout
quantity = Quantity
seller-dashboard = Seller Dashboard
post-product = Post Product
product-name = Product Name
price = Price
product-image = Product Image
order-management = Order Management
order-details = Order Details
name = Name
address = Address
phone = Phone
quantity = Quantity
price-per-item = Price per Item
total-order-price = Total Order Price
order-id=id
status= Status
sellerDashboard=Seller Dashboard
productManagement=Product Management
imageUrl = imageUrl
stockQuantity= Stock Quantity
submit = Submit
update = Update
Delivered = Delivered
Delivering = Delivering
delete= Delete
Username=Username
Password=Password
Account=Account
Language=Switch language
remove=remove
logout= Logout
Profile=My Profile
ChangePassword=Change Password
ChangeProfile=Change Profile
Enter-password=Enter password
Enter-username=Enter username
Login=Login
OldPassword=Old Password
Enter-OldPassword=Enter Old Password
NewPassword=New Password
Enter-newpassword=Enter New Password
`