export default `search-products = Tìm kiếm sản phẩm
no-products-found = Không tìm thấy sản phẩm nào.
add-to-cart = Thêm vào giỏ hàng
view-cart = Xem giỏ hàng
cart-items = Các mặt hàng trong giỏ hàng
your-cart-is-empty = Giỏ hàng của bạn đang trống.
cart = Giỏ hàng
cart-notification-count = {NUMBER($count)} sản phẩm
checkout = Thanh toán
quantity = Số lượng
seller-dashboard = Bảng điều khiển Người bán
post-product = Đăng sản phẩm
price = Giá
product-image = Hình ảnh sản phẩm
order-management = Quản lý đơn hàng
order-details = Chi tiết đơn hàng
name = Tên
address = Địa chỉ
phone = Điện thoại
product-name = Tên Sản phẩm
quantity = Số lượng
price-per-item = Giá mỗi mục
total-order-price = Tổng Giá Đơn hàng
order-id=id
status= Tình trạng
sellerDashboard= Trang tổng quan người bán
productManagement = Quản lý sản phẩm
product-detail=Chi tiết sản phẩm
stockQuantity= số lượng hàng trong kho
submit = Xác nhận
update = Cập nhật
Delivered = Đã giao hàng
Delivering = Đang giao hàng
delete=Xóa
Username=Tên đăng nhập
Password=Mật khẩu
Account=Tài khoản
Language=Chuyển ngôn ngữ
remove=xóa
logout=Đăng xuất
Profile=Thông tin tài khoản
ChangePassword = Thay đổi mật khẩu
ChangeProfile = Thay đổi thông tin cá nhân
Enter-password=Nhập mật khẩu
Enter-username=Nhập tên đăng nhập
Login=Đăng nhập
OldPassword=Mật khẩu cũ
Enter-OldPassword=Nhập mật khẩu cũ
NewPassword=Mật khẩu mới
Enter-newpassword=Nhập mật khẩu mới
Back=Quay lại
total=Tổng
detail=Mô tả
`