export default `search-products = Tìm kiếm sản phẩm
no-products-found = Không tìm thấy sản phẩm nào.
add-to-cart = Thêm vào giỏ hàng
view-cart = Xem giỏ hàng
cart-items = Các mặt hàng trong giỏ hàng
your-cart-is-empty = Giỏ hàng của bạn đang trống.
online-marketplace = Chợ trực tuyến
cart = Giỏ hàng
cart-notification-count = {NUMBER($count)} sản phẩm
checkout = Thanh toán
quantity = Số lượng
searchProducts = Tìm kiếm
seller-dashboard = Bảng điều khiển Người bán
post-product = Đăng Sản phẩm
product-name = Tên Sản phẩm
price = Giá
product-image = Hình Ảnh Sản phẩm
submit = Gửi
order-management = Quản lý Đơn hàng
order-details = Chi tiết Đơn hàng
name = Tên
address = Địa chỉ
phone = Điện thoại
product-name = Tên Sản phẩm
quantity = Số lượng
price-per-item = Giá mỗi mục
total-order-price = Tổng Giá Đơn hàng
order-id=id
status= Tình trạng
`